### ISSUE TITLE
Countess Hell Difficulty Rune Drop Rate?

### ISSUE THREAD

**Issue by Zeit42** [fearedbliss/Diablo-II--Vanilla-Frosting#1]
Hi! I'm not sure if this should be the intended behavior but I'm playing on Hell for the first time and I beat the Countess 3 times. She dropped the Nef rune twice and the Tal rune once.

I found this weird because I was getting the Amn and Ort rune on other monsters/bosses in Act 1, and if I'm not mistaken, The Countess has the highest rune drop in this act (sometimes even higher than Andariel). What is the rune drop range and rate of The Countess in Hell?

**Comment by fearedbliss** [comment]
From the front page:

- The Countess now drops up to Sol in Normal, Ist in Nightmare, and Zod in
Hell
    Before: Runes 4 [Ral], Runes 8 [Io], Runes 12 [Ist]
    After : Runes 6 [Sol], Runes 12 [Ist], Runes 17 [Zod]
- Rune drop rates have been improved.
--
This message is NOT signed or encrypted. If in doubt, please ask for a
signed reply.

Learn how to sign and encrypt your messages at
https://emailselfdefense.fsf.org/en/

Jonathan Vasquez (0xFB8590B7C4CA5279)

**Comment by Zeit42** [comment]
Oh, my bad. So it's from the bottom rune up until Zod then?

**Comment by fearedbliss** [comment]
Yup. In regular d2 it would be bottom to Ist. I just extended that range.

--
This message is NOT signed or encrypted. If in doubt, please ask for a
signed reply.

Learn how to sign and encrypt your messages at
https://emailselfdefense.fsf.org/en/

Jonathan Vasquez (0xFB8590B7C4CA5279)

**Comment by Zeit42** [comment]
Oh damn my bad. I should have been praying extra hard. Thanks for the clarification!

**Comment by fearedbliss** [comment]
Haha np

--
This message is NOT signed or encrypted. If in doubt, please ask for a
signed reply.

Learn how to sign and encrypt your messages at
https://emailselfdefense.fsf.org/en/

Jonathan Vasquez (0xFB8590B7C4CA5279)
