### ISSUE TITLE
Multiple Cow Level doesn't seem to work in 1.14D?

### ISSUE THREAD

**Issue by Zeit42** [fearedbliss/Diablo-II--Vanilla-Frosting#2]
My friend tried the Cow Level once and killed everyone. However, upon restarting the game, she could no longer access the Cow Level again. We are pretty sure she did it in the mod version because the Cube size was much bigger and she was able to open it using a single tome only.

**Comment by fearedbliss** [comment]
Vanilla frosting is only for 1.13d

--
This message is NOT signed or encrypted. If in doubt, please ask for a
signed reply.

Learn how to sign and encrypt your messages at
https://emailselfdefense.fsf.org/en/

Jonathan Vasquez (0xFB8590B7C4CA5279)
